---
# file: roles/jenkins/tasks/main.yml

- include_vars: "{{ role_path }}/defaults/{{ ansible_os_family }}_properties.yml"

- include: "{{ ansible_os_family }}_install.yml"
- include: plugins.yml
#- include: node.yml
- include: configuration.yml
- include: "{{ ansible_os_family }}_configuration.yml"
