---
# file: roles/jenkins/tasks/RedHat_install.yml

- name: "{{ ansible_os_family }} | Install | Download Jenkins Repository"
  get_url:
      url: "{{ jenkins_repository_download_url }}"
      dest: "{{ jenkins_repository_location }}"

- name: "{{ ansible_os_family }} | Install | Import Jenkins key"
  rpm_key:
      key: "https://jenkins-ci.org/redhat/jenkins-ci.org.key"

- name: "{{ ansible_os_family }} | Install | Install Jenkins"
  yum:
      name: "jenkins-{{ jenkins_version }}"
      update_cache: "yes"

- name: "{{ ansible_os_family }} | Install | Ensure Jenkins user have shell"
  user:
      name: "jenkins"
      group: "jenkins"
      createhome: yes
      home: "{{ jenkins_base_dir }}"
      shell: "/bin/bash"

- name: "{{ ansible_os_family }} | Install | Ensure Jenkins starts on reboot"
  command: "chkconfig jenkins on"

- name: "{{ ansible_os_family }} | Install | Ensure that Jenkins is started"
  service:
    name: "jenkins"
    state: "started"
