---
# file: /roles/postgres/task/RedHat_install.yml

- name: "{{ ansible_os_family }} | Ensure that repository with PostgreSQL desired version is available"
  yum:
      name: "https://download.postgresql.org/pub/repos/yum/9.4/redhat/rhel-7-x86_64/pgdg-redhat94-9.4-2.noarch.rpm"
      update_cache: "yes"

- name: "{{ ansible_os_family }} | Ensure PostgreSQL are installed"
  yum:
      name: "{{ item }}"
      update_cache: yes
  with_items:
      - "postgresql{{ postgres_major_version }}{{ postgres_minor_version }}-server"
      - "postgresql{{ postgres_major_version }}{{ postgres_minor_version }}-contrib"
      - "python-psycopg2" # Necessary to use "postgresql_db" "postgresql_user"


- name: "Check if OS distribution specific install exists"
  become: No
  local_action: stat path="{{ role_path }}/tasks/{{ ansible_os_family }}/{{ ansible_distribution }}_install.yml"
  register: "os_dist_specific_install"

- include: "{{ ansible_os_family }}/{{ ansible_distribution }}_install.yml"
  when: os_dist_specific_install.stat.exists
