---
- hosts: test
  become: true
  remote_user: root
  roles:
    - ansible-oracle-java
  vars:
    java_major_version: "{{ lookup('env','java_major') }}"
    java_minor_version: "{{ lookup('env','java_minor') }}"
