---
dependencies: []

galaxy_info:
  author: opdavies
  description: Mantis Bug Tracker for RedHat/CentOS/Debian/Ubuntu.
  min_ansible_version: 1.4
  platforms:
    - name: EL
      versions:
        - 6
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  categories:
    - web
