---
- name: Create Mantis database.
  sudo: yes
  mysql_db:
    name: "{{ mantis_db_name }}"
    state: present
  when: mantis_create_db
  register: mantis_db_created

- name: Check for the database install script.
  stat:
    path: "{{ mantis_db_path }}"
  register: mantis_db_tmp_path

- name: Copy database install script.
  template:
    src: install.sql.j2
    dest: "{{ mantis_db_path }}"
  when: mantis_install_db and not mantis_db_tmp_path.stat.exists

- name: Install Mantis database.
  sudo: yes
  mysql_db:
    name: "{{ mantis_db_name }}"
    state: import
    target: "{{ mantis_db_path }}"
  when: mantis_db_created.changed

- name: Create Mantis database user.
  sudo: yes
  mysql_user:
    name: "{{ mantis_db_user }}"
    password: "{{ mantis_db_pass }}"
    priv: "{{ mantis_db_name }}.*:ALL"
    state: present
  when: mantis_db_created.changed
