# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "geerlingguy/centos7"

  config.vm.network "private_network", ip: "10.0.0.82"

  config.vm.synced_folder ".", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
     # Customize the amount of memory on the VM:
    vb.memory = 4096
    vb.cpus = 2
   end

   config.vm.provision "shell", privileged: false, inline: <<-SHELL
     sudo nmcli connection reload
     sudo systemctl restart network.service

    SHELL

    config.vm.provision "ansible_local" do |ansible|
        ansible.provisioning_path = "/vagrant_data"
        ansible.playbook = "/vagrant_data/provisioning.yml"
        ansible.galaxy_role_file = "/vagrant_data/requirements.yml"
    end

end
