version: '3'

services:
  
  devops-web-master:
    image: local.nexus.com:8083/devops/devops-web:${APP_VERSION}
    ports:
    - "8989:80"
    networks:
    - devops-web-master

networks:
  devops-web-master:
