version: '3'

services:
  
  devops-db-test:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: 'devops'
      MYSQL_USER: 'devops'
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    networks:
    - devops
  
volumes:
  db_data:

networks:
  devops:
  