---
# file: /roles/maven/tasks/install.yml

- name: "Install | Download Maven"
  get_url:
      url: "{{ maven_download_url }}"
      dest: "/tmp/{{ maven_file }}"
      timeout: 60

# We do not use unarchive because it fails to untar the target tar.gz
- name: "Install | Extract Maven"
  command: "tar -xzvf /tmp/{{ maven_file }} -C /opt"

- name: "Install | Create link to Maven folder"
  file:
      src: "{{ maven_home }}"
      dest: "/opt/maven"
      state: link

- name: "Install | Tell the machine to use our Maven"
  alternatives:
      name: "mvn"
      link: "/usr/bin/mvn"
      path: "/opt/maven/bin/mvn"
